# Generated by Django 4.2 on 2023-04-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuditDate', models.DateTimeField(auto_now_add=True)),
                ('CaseNumber', models.IntegerField()),
                ('PolicyNumber', models.CharField(max_length=12)),
                ('AVS', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=5)),
                ('debit_date', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=20)),
                ('start_date', models.CharField(choices=[('1st_Jan', '1st of January'), ('1st_Feb', '1st of February'), ('1st_Mar', '1st of March'), ('1st_Apr', '1st of April'), ('1st_May', '1st of May'), ('1st_June', '1st of June'), ('1st_July', '1st of July'), ('1st_Aug', '1st of August'), ('1st_Sept', '1st of September'), ('1st_Oct', 'October'), ('1st_Nov', '1st of November'), ('1st_Dec', '1st of December')], max_length=20)),
                ('Caller_id', models.CharField(max_length=50)),
                ('QA_Outcome', models.CharField(choices=[('Zero-defect', 'Zero-defect'), ('Defective', 'Defective'), ('CAT_1', 'CAT_1')], max_length=20)),
                ('QAC_Correction', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('KPA', models.CharField(choices=[('Product', 'Product'), ('Pass', 'Pass'), ('Compliance', 'Compliance'), ('Data Capturing', 'Data Capturing'), ('TCF', 'TCF')], max_length=50)),
                ('Comment', models.TextField(max_length=200)),
                ('Sales_agent', models.CharField(max_length=50)),
            ],
        ),
    ]
