# Generated by Django 4.2 on 2023-04-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southsideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaaudit',
            name='start_date',
            field=models.CharField(choices=[('1st_Jan', '1st of January'), ('1st_Feb', '1st of February'), ('1st_Mar', '1st of March'), ('1st_Apr', '1st of April'), ('1st_May', '1st of May'), ('1st_June', '1st of June'), ('1st_July', '1st of July'), ('1st_Aug', '1st of August'), ('1st_Sept', '1st of September'), ('1st_Oct', 'st of October'), ('1st_Nov', '1st of November'), ('1st_Dec', '1st of December')], max_length=20),
        ),
    ]
