# Generated by Django 4.2 on 2023-04-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('southsideapp', '0005_qaaudit_qa_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaaudit',
            name='Cover_amount',
            field=models.CharField(default=False, max_length=13),
        ),
        migrations.AddField(
            model_name='qaaudit',
            name='Premium',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='qaaudit',
            name='sales_date',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='KPA',
            field=models.CharField(choices=[('Product', 'Product'), ('Pass', 'Pass'), ('Compliance', 'Compliance'), ('Data Capturing', 'Data Capturing'), ('TCF', 'TCF'), ('Underwriting', 'Underwriting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='QA_Audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
