# Generated by Django 4.2 on 2023-04-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southsideapp', '0007_alter_qaaudit_avs_alter_qaaudit_caller_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaaudit',
            name='AVS',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='Caller_id',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='CaseNumber',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='Cover_amount',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='KPA',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='PolicyNumber',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='Premium',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='QAC_Correction',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='QA_Audit',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='QA_Outcome',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='Sales_agent',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='debit_date',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='sales_date',
        ),
        migrations.RemoveField(
            model_name='qaaudit',
            name='start_date',
        ),
    ]
