# Generated by Django 4.2 on 2023-04-26 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('southsideapp', '0009_qaaudit_avs_qaaudit_caller_id_qaaudit_casenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaaudit',
            name='AVS',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='Caller_id',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='CaseNumber',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='Comment',
            field=models.TextField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='Cover_amount',
            field=models.CharField(default=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='KPA',
            field=models.CharField(choices=[('Product', 'Product'), ('Pass', 'Pass'), ('Compliance', 'Compliance'), ('Data Capturing', 'Data Capturing'), ('TCF', 'TCF'), ('Underwriting', 'Underwriting')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='PolicyNumber',
            field=models.CharField(default=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='Premium',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='QAC_Correction',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='QA_Audit',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='QA_Outcome',
            field=models.CharField(choices=[('Zero-defect', 'Zero-defect'), ('Defective', 'Defective'), ('CAT_1', 'CAT_1')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='Sales_agent',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='debit_date',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='sales_date',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='start_date',
            field=models.CharField(choices=[('1st_Jan', '1st of January'), ('1st_Feb', '1st of February'), ('1st_Mar', '1st of March'), ('1st_Apr', '1st of April'), ('1st_May', '1st of May'), ('1st_June', '1st of June'), ('1st_July', '1st of July'), ('1st_Aug', '1st of August'), ('1st_Sept', '1st of September'), ('1st_Oct', '1st of October'), ('1st_Nov', '1st of November'), ('1st_Dec', '1st of December')], default=True, max_length=20),
        ),
    ]
