# Generated by Django 4.2 on 2023-04-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southsideapp', '0011_alter_qaaudit_avs_alter_qaaudit_caller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaaudit',
            name='Duration',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='qaaudit',
            name='KPA_1',
            field=models.CharField(choices=[('Product', 'Product'), ('Pass', 'Pass'), ('Compliance', 'Compliance'), ('Data Capturing', 'Data Capturing'), ('TCF', 'TCF'), ('Underwriting', 'Underwriting')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qaaudit',
            name='KPA_2',
            field=models.CharField(choices=[('Product', 'Product'), ('Pass', 'Pass'), ('Compliance', 'Compliance'), ('Data Capturing', 'Data Capturing'), ('TCF', 'TCF'), ('Underwriting', 'Underwriting')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qaaudit',
            name='KPA_3',
            field=models.CharField(choices=[('Product', 'Product'), ('Pass', 'Pass'), ('Compliance', 'Compliance'), ('Data Capturing', 'Data Capturing'), ('TCF', 'TCF'), ('Underwriting', 'Underwriting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qaaudit',
            name='QA_Outcome',
            field=models.CharField(choices=[('Zero-defect', 'Zero-defect'), ('Defective', 'Defective'), ('Refer to Commit', 'Refer to Commit')], max_length=20),
        ),
    ]
